In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
             [4,5,6]],dtype="int64")
b = np.array([[7,8,9],
             [10,11,12]],dtype="int64")
a + b, a*b, a-b

(array([[ 8, 10, 12],
        [14, 16, 18]], dtype=int64),
 array([[ 7, 16, 27],
        [40, 55, 72]], dtype=int64),
 array([[-6, -6, -6],
        [-6, -6, -6]], dtype=int64))

In [19]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [21]:
(a**b).dtype , a**b


(dtype('int64'),
 array([[         1,        256,      19683],
        [   1048576,   48828125, 2176782336]], dtype=int64))

In [11]:
6**12, 5**11, 3**9, 4**10, 

(2176782336, 48828125, 19683, 1048576)

In [23]:
a%b, b//a

(array([[1, 2, 3],
        [4, 5, 6]], dtype=int64),
 array([[7, 4, 3],
        [2, 2, 2]], dtype=int64))

<Font Size = 5.5> Arithmetic operations with scalars propagate the scalar argument to each element in the array. <br> <br> 
    Operations between differently sized arrays is called Broadcasting.

In [24]:
a*2  ### Broadcasting

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int64)

In [25]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]], dtype=int64)

In [26]:
a - np.array(3)

array([[-2, -1,  0],
       [ 1,  2,  3]], dtype=int64)

In [30]:
a/4, a**3, a+5

(array([[0.25, 0.5 , 0.75],
        [1.  , 1.25, 1.5 ]]),
 array([[  1,   8,  27],
        [ 64, 125, 216]], dtype=int64),
 array([[ 6,  7,  8],
        [ 9, 10, 11]], dtype=int64))

<Font Size = 5.5> Universal Functions <Br> <Br> <Font size = 5> A universal function or ufunc, is a function that performs element-wise operations on data in ndarrays.

In [3]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

np.add(x,y)         #### Or x+y   or y+x

array([ 7,  9, 11, 13, 15])

In [35]:
np.subtract(y,x)   ### y-x

array([5, 5, 5, 5, 5])

In [39]:
np.sqrt(x),np.mod(y,x),y%x

(array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798]),
 array([0, 1, 2, 1, 0]),
 array([0, 1, 2, 1, 0]))

<Font Size = 5.5> Pseudo-Random Number Generation 

In [4]:
### In PYthon we have a built-in module random.

import random
import numpy as np

random.random()                 ### Different Number Every time......seed() value is not FIXED!

0.706831958126103

In [5]:
random.seed(2)            
random.random()                ### Same number is generated as seed() Value is fixed NOW!....

0.9560342718892494

In [6]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [7]:
np.random.seed(33)
np.random.random()

0.24851012743772993

In [8]:
np.random.seed(1)
np.random.random()

0.417022004702574