In [1]:
import numpy as np

In [2]:
ar1 = np.array([["Hello", "World"],["xyz"]])
ar1

C:\Users\user\AppData\Local\Temp\ipykernel_11380\2023276504.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar1 = np.array([["Hello", "World"],["xyz"]])


array([list(['Hello', 'World']), list(['xyz'])], dtype=object)

In [3]:
ar1.ndim           #### Length of the lists must be same........... Converted to one-dimensional array......

1

In [2]:
x = np.array([1,2,3,4,-5], dtype="object")
x, x.dtype

(array([1, 2, 3, 4, -5], dtype=object), dtype('O'))

In [3]:
x = np.array([1,2,3,4,-5], dtype="U")
x, x.dtype

(array(['1', '2', '3', '4', '-5'], dtype='<U2'), dtype('<U2'))

In [4]:
x = np.array([1,2,3,4,-5], dtype="S")
x, x.dtype

(array([b'1', b'2', b'3', b'4', b'-5'], dtype='|S2'), dtype('S2'))

In [5]:
x = np.array([1,2,3,4,-5], dtype="int")
x, x.dtype

(array([ 1,  2,  3,  4, -5]), dtype('int32'))

In [6]:
x = np.array([1,2,3,4,-5], dtype="uint")
x, x.dtype

(array([         1,          2,          3,          4, 4294967291],
       dtype=uint32),
 dtype('uint32'))

In [7]:
x = np.array([1,2,3,4,-5], dtype="int64")
x, x.dtype

(array([ 1,  2,  3,  4, -5], dtype=int64), dtype('int64'))

In [8]:
x = np.array([1,2,3,4,-5], dtype="f4")
x, x.dtype

(array([ 1.,  2.,  3.,  4., -5.], dtype=float32), dtype('float32'))

In [9]:
x = np.array([1,2,3,4,-5], dtype="int8")
x, x.dtype

(array([ 1,  2,  3,  4, -5], dtype=int8), dtype('int8'))

In [10]:
x = np.array([1,2,3,4,-5], dtype="u1")
x, x.dtype

(array([  1,   2,   3,   4, 251], dtype=uint8), dtype('uint8'))

In [11]:
x = np.array([1,2,3,4,-5], dtype="bool")
x, x.dtype

(array([ True,  True,  True,  True,  True]), dtype('bool'))

In [12]:
x = np.array([1,2,3,4,-5], dtype="c8")
x, x.dtype

(array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j, -5.+0.j], dtype=complex64),
 dtype('complex64'))

<font size = 5.5> Use of NumPy -- Numerical Computation <font size = 4> <br> Runtime of programme is reduced <br> Takes less space (memory space)

In [14]:
x = np.array([1,2,3555555555555555,4,-5], dtype="int32")
x, x.dtype

OverflowError: Python int too large to convert to C long

In [16]:
x = np.array([1,2,35555555555555555555555555,4,-5], dtype="int64")
x, x.dtype

OverflowError: int too big to convert

In [3]:
x = np.array(["Hello","Data","Scientist","Aj","SS"], dtype="U") ## Maximum length of a string in this ndarray
x, x.dtype                                                      ## Length of string longest string is 9

(array(['Hello', 'Data', 'Scientist', 'Aj', 'SS'], dtype='<U9'), dtype('<U9'))

In [19]:
x = np.array(["Hello","Data","Scientist","Hello Data"], dtype="U") ## Maximum length of a string in this ndarray
x, x.dtype                                                         ## Length of string longest string is 10

(array(['Hello', 'Data', 'Scientist', 'Hello Data'], dtype='<U10'),
 dtype('<U10'))

In [24]:
len("Scientist","Hello Data")

TypeError: len() takes exactly one argument (2 given)

In [25]:
len("Scientist")

9

<font size = 5.5> NumPy Array Inspection ........,".ndim", ".shape", ".dtype", ".size"

In [6]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([1,2,3,4])
x.ndim

1

In [29]:
x

array([1, 2, 3, 4])

In [28]:
x.shape

(4,)

In [4]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[1,2,3,4],[5,6,7,8]])
x.ndim

2

In [5]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
x.shape           ## (Row , Column) = (2,4)

(2, 4)

In [7]:
x.shape = (2,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
x.ndim

3

In [11]:
x.size

8

In [9]:
x.ndim.size

AttributeError: 'int' object has no attribute 'size'

In [5]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[1,2,3],[5,6,7]])
x.ndim, x.size

(2, 6)

In [35]:
x

array([[1, 2, 3],
       [5, 6, 7]])

In [36]:
x.shape          ## (Row , Column) = (2,3)  --- gives value in tuple

(2, 3)

In [6]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[1,2,3],[5,6,7]], [[1,2,3],[5,6,7]], [[1,2,3],[5,6,7]]])
x.ndim, x.shape, x.size

(3, (3, 2, 3), 18)

In [7]:
x

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [7]:
# ndarray.ndim - Returns the number of dimensions
x = np.array([[[[1,2,3,4],[5,6,7,8]]]])
print(x.ndim)
x.shape

4


(1, 1, 2, 4)

In [8]:
x

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [4]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[1,2,3,4]]],[[[5,6,7,8]]]])
print(x.ndim)
x.shape

4


(2, 1, 1, 4)

In [8]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[1,2,3,4]],[[5,6,7,8]]]])
print(x.ndim)
x.shape

4


(1, 2, 1, 4)

In [10]:
x

array([[[[1, 2, 3, 4]],

        [[5, 6, 7, 8]],

        [[1, 2, 3, 4]]]])

In [11]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[1,2,3,4]],[[5,6,7,8]],[[1,2,3,4]]]])
print(x.ndim)
x.shape

4


(1, 3, 1, 4)

In [9]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]]])
print(x.ndim)
x.shape

4


(3, 2, 1, 4)

In [10]:
x

array([[[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]],


       [[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]],


       [[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]]])

<font size  = 5.5> 19 Sept 2023

In [15]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]]]])
print(x.ndim)
x.shape

5


(1, 3, 2, 1, 4)

In [16]:
x

array([[[[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]],


        [[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]],


        [[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]]]])

In [11]:
## ndarray.ndim - Returns the number of dimensions
x = np.array([[[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]],[[[1,2,3,4]],[[5,6,7,8]]]]])
print(x.ndim)
x.shape

5


(1, 4, 2, 1, 4)

In [12]:
x

array([[[[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]],


        [[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]],


        [[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]],


        [[[1, 2, 3, 4]],

         [[5, 6, 7, 8]]]]])

In [22]:
a = [1,2,3,4]
b = [11,22,33,44]
c = [5,6,7,8]
d = [55,66,77,88]

aa = np.array([[a,b,c,d]])
aa.shape

(1, 4, 4)

In [23]:
a = [1,2,3,4]
b = [11,22,33,44]
c = [5,6,7,8]
d = [55,66,77,88]

aa = np.array([[a,b,c,d],[a,b,c,d],[a,b,c,d],[a,b,c,d]])
aa.shape

(4, 4, 4)

In [26]:
aa = np.array([[[a,b],[c,d]],[[a,b],[c,d]],[[a,b],[c,d]]])
print(aa)
aa.shape

[[[[ 1  2  3  4]
   [11 22 33 44]]

  [[ 5  6  7  8]
   [55 66 77 88]]]


 [[[ 1  2  3  4]
   [11 22 33 44]]

  [[ 5  6  7  8]
   [55 66 77 88]]]


 [[[ 1  2  3  4]
   [11 22 33 44]]

  [[ 5  6  7  8]
   [55 66 77 88]]]]


(3, 2, 2, 4)

In [28]:
aa = np.array([[[a,b,c],[a,c,d]],[[a,b,d],[b,c,d]],[[a,b,c],[c,d,b]],[[a,b,c],[c,d,b]]])
print(aa)
aa.shape

[[[[ 1  2  3  4]
   [11 22 33 44]
   [ 5  6  7  8]]

  [[ 1  2  3  4]
   [ 5  6  7  8]
   [55 66 77 88]]]


 [[[ 1  2  3  4]
   [11 22 33 44]
   [55 66 77 88]]

  [[11 22 33 44]
   [ 5  6  7  8]
   [55 66 77 88]]]


 [[[ 1  2  3  4]
   [11 22 33 44]
   [ 5  6  7  8]]

  [[ 5  6  7  8]
   [55 66 77 88]
   [11 22 33 44]]]


 [[[ 1  2  3  4]
   [11 22 33 44]
   [ 5  6  7  8]]

  [[ 5  6  7  8]
   [55 66 77 88]
   [11 22 33 44]]]]


(4, 2, 3, 4)

In [29]:
a = [1,2,3,4]
b = [11,22,33,44]
c = [5,6,7,8]
d = [55,66,77,88]
e = [1,3,5,7]
f = [11,55,77,99]
aa = np.array([[a,b,c,d,e]])
aa.shape

(1, 5, 4)

In [42]:
a = [1,2,3,4,5]
b = [11,22,33,44,55]
c = [5,6,7,8,9]
d = [55,66,77,88,99]
e = [1,3,5,7,9]
f = [11,55,77,99,33]
aa = np.array([[[a,b,c],[d,e,f]]])
aa.shape

(1, 2, 3, 5)

In [37]:
a = [1,2,3,4,5]
b = [11,22,33,44,55]
c = [5,6,7,8,9]
d = [55,66,77,88,99]
e = [1,3,5,7,9]
f = [11,55,77,99,33]
aa = np.array([[a,b,c],[d,e,f]])
aa.shape

(2, 3, 5)

In [39]:
aa

array([[[ 1,  2,  3,  4,  5],
        [11, 22, 33, 44, 55],
        [ 5,  6,  7,  8,  9]],

       [[55, 66, 77, 88, 99],
        [ 1,  3,  5,  7,  9],
        [11, 55, 77, 99, 33]]])

In [43]:
bb = np.array([[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]])
bb.shape

(3, 5)

In [44]:
bb = np.array([[[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]],[[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]]])
bb.shape

(2, 3, 5)

In [14]:
bb = np.array([[[[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]],[[1,2,3,4,5],[1,2,3,4,5],[2,3,4,5,6]]]])
bb.shape

(1, 2, 3, 5)

In [54]:
bb = bb.reshape(1,1,2,15)

In [15]:
bb

array([[[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6]]]])

<font size = 5.5> .reshape().....Method...

In [56]:
bb.reshape(5,2,3)

array([[[1, 2, 3],
        [4, 5, 1]],

       [[2, 3, 4],
        [5, 2, 3]],

       [[4, 5, 6],
        [1, 2, 3]],

       [[4, 5, 1],
        [2, 3, 4]],

       [[5, 2, 3],
        [4, 5, 6]]])

In [57]:
bb.reshape(2,2,5)

ValueError: cannot reshape array of size 30 into shape (2,2,5)

In [58]:
bb.reshape(5,3,2)

array([[[1, 2],
        [3, 4],
        [5, 1]],

       [[2, 3],
        [4, 5],
        [2, 3]],

       [[4, 5],
        [6, 1],
        [2, 3]],

       [[4, 5],
        [1, 2],
        [3, 4]],

       [[5, 2],
        [3, 4],
        [5, 6]]])

In [59]:
bb.reshape(1,6,5)

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]]])

In [46]:
bb = np.array([[[[1,2,3,4,5,1,2,3,4,5],[2,3,4,5,6,1,2,3,4,5],[1,2,3,4,5,2,3,4,5,6]]]])
bb.shape

(1, 1, 3, 10)

In [48]:
bb = np.array([[[1,2,3,4,5,1,2,3,4,5],[2,3,4,5,6,1,2,3,4,5],[1,2,3,4,5,2,3,4,5,6]]])
bb.shape

(1, 3, 10)

In [47]:
bb = np.array([[[1,2,3,4,5,1,2,3,4,5,2,3,4,5,6,1,2,3,4,5,1,2,3,4,5,2,3,4,5,6]]])
bb.shape

(1, 1, 30)

<font size  = 5.5> Number of elements in (2,3,5) = (2 multiply 3 multiply 5) = 30

In [50]:
2*3*5

30

<font size = 5.5> 20 Sept 2023

In [16]:
## Change the shape of an ndarray.

import numpy as np
x = np.array([1,2,3,4])
print(x.shape)
print(x)
## 2*2 = 4
x.shape = (2,3)

(4,)
[1 2 3 4]


ValueError: cannot reshape array of size 4 into shape (2,3)

In [17]:
## Change the shape of an ndarray.

import numpy as np
x = np.array([1,2,3,4])
print(x.shape)
print(x)
## 2*2 = 4
x.shape = (1,1,4)
x

(4,)
[1 2 3 4]


array([[[1, 2, 3, 4]]])

In [6]:
## Change the shape of an ndarray.

import numpy as np
x = np.array([1,2,3,4])
print(x.shape)
print(x)
## 2*2 = 4
x.shape = (1,2,1,2)
x

(4,)
[1 2 3 4]


array([[[[1, 2]],

        [[3, 4]]]])

In [8]:
x.shape = (2,2,1,1)
x

array([[[[1]],

        [[2]]],


       [[[3]],

        [[4]]]])

In [9]:
x.shape = (0,1,2,2)

ValueError: cannot reshape array of size 4 into shape (0,1,2,2)

In [13]:
x.shape = (2,2,1,1,1,1)
x

array([[[[[[1]]]],



        [[[[2]]]]],




       [[[[[3]]]],



        [[[[4]]]]]])

In [15]:
x.shape = (2,1,1,1,1,2)         ## six - dimensional - number of values tells the number of dimensions
x

array([[[[[[1, 2]]]]],




       [[[[[3, 4]]]]]])

In [18]:
x = print(x.reshape (1,1,1,1,1,1,1,4))
x.ndim

[[[[[[[[1 2 3 4]]]]]]]]


AttributeError: 'NoneType' object has no attribute 'ndim'

<font size = 4.5> Shape of an ndarray also gives its size and number of dimentions. <br><br> For size, multiply the values in the shape e.g. (2,3) --- 2*3 = 6 <br> <br> For dimensions, count the number of values in the shape tuple e.g. (2,3) -- 2 Dimensional. <br><br> While changing the shape of an array keep in mind that its size i.e. number of elements **will not change.**

In [8]:
x = np.array([1,2,3,4])
x = x.reshape (1,1,1,1,1,1,1,4)
x.ndim

8

In [9]:
x

array([[[[[[[[1, 2, 3, 4]]]]]]]])

In [29]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (2,2,2)
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (2,4)
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (1,1,8)
y

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [32]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (4,2,1)
y

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [10]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (8,1,1)
y

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [12]:
y.shape = (1,1,8)
y

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [36]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (1,1,2,2,1,2)
print(y)
y.ndim

[[[[[[1 2]]

    [[3 4]]]


   [[[5 6]]

    [[7 8]]]]]]


6

In [37]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (2,1,2,2)
y

array([[[[1, 2],
         [3, 4]]],


       [[[5, 6],
         [7, 8]]]])

In [38]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (4,2)
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (1,2,4)
y

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [41]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (2,2,1,2)
y

array([[[[1, 2]],

        [[3, 4]]],


       [[[5, 6]],

        [[7, 8]]]])

In [42]:
y = np.array([1,2,3,4,5,6,7,8])
y.shape = (1,2,2,2)
y

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

<font size = 5.5> 21 Sept 2023 <br><br> .size <br>.dtype

In [1]:
## ndarray.size  --- Returns the number of elements.
import numpy as np
x = np.array([1,2,3,4,5,6,7])
x.size

7

In [2]:
## ndarray.dtype  --- Returns the data type of the elements in the ndarray.
x.dtype

dtype('int32')

<font size = 5.5> Methods and Functions used with ndarrays <br> <br> np.ones(shape,dtype)

In [4]:
## np.ones(shape,dtype)  - Retuns a new array of given shape and type, filled with ones.
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
np.ones((2,2,2)).dtype

dtype('float64')

In [15]:
y = np.ones((2,2,2)).dtype
y

dtype('float64')

<font size  = 4.5> Data Type of ... dtype('float64')........is -->  numpy.dtype[float64] and It is an "Object...of PYthon"

In [16]:
y = np.ones((2,2,2)).dtype
type(y)

numpy.dtype[float64]

In [17]:
y = np.ones((2,2,2)).ndim
type(y)

int

In [18]:
y = np.ones((2,2,2)).size
type(y)

int

In [19]:
y = np.ones((2,2,2)).shape
type(y)

tuple

In [6]:
np.ones((2,2,2),(dtype32))

NameError: name 'dtype32' is not defined

In [12]:
np.ones((2,2,2), (dtype="int32"))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1641567541.py, line 1)

In [10]:
np.ones((2,2,2), (dtype="int64"))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2460757158.py, line 1)

In [13]:
np.ones((2,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [12]:
np.ones((2,2,2), dtype="U")

array([[['1', '1'],
        ['1', '1']],

       [['1', '1'],
        ['1', '1']]], dtype='<U1')

In [17]:
np.ones((2,2,2), dtype="int64")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int64)

In [68]:
np.ones((2,2,2),"int64")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int64)

In [69]:
np.ones((2,2,2),"complex")

array([[[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j]]])

<Font size = 5.5> np.zeros(shape,dtype)

In [71]:
np.zeros((2,1,1,5),"U2")

array([[[['', '', '', '', '']]],


       [[['', '', '', '', '']]]], dtype='<U2')

In [20]:
## np.zeros (shape,dtype)        ---- Returns a new array of given shape type, filled with zeros. 
np.zeros((2,1,1,5))

array([[[[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]]]])

In [70]:
np.zeros((2,1,1,5),"int8")

array([[[[0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0]]]], dtype=int8)

<font size = 5> np.empty(shape,dtype) <br> np.empty <br> np.full

In [21]:
## np.empty(shape,dtype)  
## Returns a new array of given shape and type, without initializing entries.
np.empty((2,1),dtype = "U")

array([[''],
       ['']], dtype='<U1')

In [26]:
## np.empty(shape,dtype)  
## Returns a new array of given shape and type, without initializing entries.
np.empty((2,1),dtype = "uint")

array([[ 538976496],
       [1646292852]], dtype=uint32)

In [29]:
## np.empty(shape,dtype)  
## Returns a new array of given shape and type, without initializing entries.
np.empty((2,1,2),dtype = "complex")

array([[[0.00000000e+000+0.0000000e+000j,
         0.00000000e+000+0.0000000e+000j]],

       [[0.00000000e+000+7.0552574e-321j,
         6.23057348e-307+1.4241953e-306j]]])

In [66]:
np.empty((2,1,2),"complex")

array([[[1.+1.j, 1.+1.j]],

       [[1.+1.j, 1.+1.j]]])

In [67]:
np.empty((2,1,2),"uint")

array([[[3550589296,        383]],

       [[         0,          0]]], dtype=uint32)

<font size = 5> np.full(shape,fill_value,dtype)

In [30]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,3,4),9,dtype="int")

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [20]:
np.full((2,3,4),"PYthon",dtype="S")

array([[[b'P', b'P', b'P', b'P'],
        [b'P', b'P', b'P', b'P'],
        [b'P', b'P', b'P', b'P']],

       [[b'P', b'P', b'P', b'P'],
        [b'P', b'P', b'P', b'P'],
        [b'P', b'P', b'P', b'P']]], dtype='|S1')

In [24]:
np.full((2,3,4),"Tavishi",dtype="U")

array([[['T', 'T', 'T', 'T'],
        ['T', 'T', 'T', 'T'],
        ['T', 'T', 'T', 'T']],

       [['T', 'T', 'T', 'T'],
        ['T', 'T', 'T', 'T'],
        ['T', 'T', 'T', 'T']]], dtype='<U1')

In [26]:
np.full((2,3,4),"Tavi")

array([[['Tavi', 'Tavi', 'Tavi', 'Tavi'],
        ['Tavi', 'Tavi', 'Tavi', 'Tavi'],
        ['Tavi', 'Tavi', 'Tavi', 'Tavi']],

       [['Tavi', 'Tavi', 'Tavi', 'Tavi'],
        ['Tavi', 'Tavi', 'Tavi', 'Tavi'],
        ['Tavi', 'Tavi', 'Tavi', 'Tavi']]], dtype='<U4')

In [22]:
np.full((2,3,4),"PYthon",dtype="int")

ValueError: invalid literal for int() with base 10: 'PYthon'

In [21]:
np.full((2,3,4),"AJ",dtype="S")

array([[[b'A', b'A', b'A', b'A'],
        [b'A', b'A', b'A', b'A'],
        [b'A', b'A', b'A', b'A']],

       [[b'A', b'A', b'A', b'A'],
        [b'A', b'A', b'A', b'A'],
        [b'A', b'A', b'A', b'A']]], dtype='|S1')

In [13]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,3,4),"AAAA",dtype="U")

array([[['A', 'A', 'A', 'A'],
        ['A', 'A', 'A', 'A'],
        ['A', 'A', 'A', 'A']],

       [['A', 'A', 'A', 'A'],
        ['A', 'A', 'A', 'A'],
        ['A', 'A', 'A', 'A']]], dtype='<U1')

In [14]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,2,2),"ABCD",dtype="U5")

array([[['ABCD', 'ABCD'],
        ['ABCD', 'ABCD']],

       [['ABCD', 'ABCD'],
        ['ABCD', 'ABCD']]], dtype='<U5')

In [43]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,1,2),"SS",dtype="U2")

array([[['SS', 'SS']],

       [['SS', 'SS']]], dtype='<U2')

In [41]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,2,2),"18",dtype="U2")

array([[['18', '18'],
        ['18', '18']],

       [['18', '18'],
        ['18', '18']]], dtype='<U2')

In [42]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,2,2),"18",dtype="int16")

array([[[18, 18],
        [18, 18]],

       [[18, 18],
        [18, 18]]], dtype=int16)

In [64]:
np.full((2,2,2),"18","int16")

array([[[18, 18],
        [18, 18]],

       [[18, 18],
        [18, 18]]], dtype=int16)

In [65]:
np.full((2,2,2),"18","int8")

array([[[18, 18],
        [18, 18]],

       [[18, 18],
        [18, 18]]], dtype=int8)

In [46]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full(dtype="int16")

TypeError: full() missing 2 required positional arguments: 'shape' and 'fill_value'

In [47]:
## np.full(shape,fill_value,dtype)
## Returns a new array of given shape and type, filled with fill_value

np.full((2,3,4),9).dtype

dtype('int32')

In [49]:
np.full((2,2,4),9).size

16

In [50]:
np.full((2,2,4),9).shape

(2, 2, 4)

In [51]:
np.full((2,2,4),9).ndim

3

In [52]:
np.empty((2,2,2)).dtype

dtype('float64')

In [53]:
np.empty((2,2,2)).ndim

3

In [54]:
np.empty((2,2,2)).size

8

In [55]:
np.empty((2,2,2)).shape

(2, 2, 2)

In [56]:
np.ones((2,2,2)).dtype

dtype('float64')

In [57]:
np.ones((2,2,2)).ndim

3

In [58]:
np.ones((2,2,2)).empty

AttributeError: 'numpy.ndarray' object has no attribute 'empty'

In [59]:
np.ones((2,2,2)).full

AttributeError: 'numpy.ndarray' object has no attribute 'full'

In [60]:
np.ones((2,2,2)).reshape(1,1,8)

array([[[1., 1., 1., 1., 1., 1., 1., 1.]]])

In [61]:
np.ones((2,2,2)).empty((1,1,8))

AttributeError: 'numpy.ndarray' object has no attribute 'empty'

In [62]:
y = np.array([1,2,3,4,5])
y.dtype

dtype('int32')

In [63]:
np.array([1,2,3,4,5]).dtype

dtype('int32')

<font size = 5.5> 22_Sept_2023

<font size = 5.5>  --- np.arange(start,stop,step,dtype).....syntax

In [16]:
## np.arange(start,stop,step,dtype)
## Returns enenly spaced values within a given interval.
#### Stop value is excluded........
#### Step is controlled by us......
import numpy as np
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [28]:
### Can we use floating point--start,stop,step?
np.arange(2.2,12.2,2.2)

array([ 2.2,  4.4,  6.6,  8.8, 11. ])

In [2]:
list(range(3,10,2))

[3, 5, 7, 9]

In [3]:
list(range(3,10.2,2))

TypeError: 'float' object cannot be interpreted as an integer

In [4]:
np.arange(2,11.2,2)

array([ 2.,  4.,  6.,  8., 10.])

In [5]:
np.arange(2,11.2,2.1)

array([ 2. ,  4.1,  6.2,  8.3, 10.4])

In [6]:
np.arange(a,j,2)

NameError: name 'a' is not defined

In [7]:
## Can we use floating point start, stop and step? ------- Yes
np.arange(2.1,13.2,2.2)

array([ 2.1,  4.3,  6.5,  8.7, 10.9, 13.1])

In [8]:
np.arange(2.1,13.2,2.2,int)

array([ 2,  4,  6,  8, 10, 12])

In [9]:
np.arange(2.1,13.2,2.2,uint)

NameError: name 'uint' is not defined

In [10]:
np.arange(2.1,13.2,2.2,bool)

ValueError: no fill-function for data-type.

In [11]:
np.arange(2.1,13.2,2.2,complex)

array([ 2.1+0.j,  4.3+0.j,  6.5+0.j,  8.7+0.j, 10.9+0.j, 13.1+0.j])

In [13]:
np.arange(2,13,2,dtype="float")

array([ 2.,  4.,  6.,  8., 10., 12.])

In [14]:
np.arange(15,13,2,bool)

array([], dtype=bool)

<font size = 5.5> ----  np.linspace

In [27]:
## np.linspace(start,stop,num=50,endpoint=True,dtype)
## Returns evenly spaced numbers over a specified interval.


#### What do num=50 and endpoint=True suggest here? 
## endpoint=Ture  ----- stop value is inclued....
## endpoint=False  ----- stop value is Exclued....
## Defaul num=50 is the default value and gives 50 numbers in between start and stop values....
#### num=50 is the defaut value of num when not given i.e. , it will give 50 numbers in the range....
#### endpoint=True is the default value of endpoint which tells us that the stop value is inclusive by Default....

print(np.linspace(2,10).size)
np.linspace(2,10)

50


array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [16]:
np.linspace(2,10,7,endpoint=False)

array([2.        , 3.14285714, 4.28571429, 5.42857143, 6.57142857,
       7.71428571, 8.85714286])

In [17]:
np.linspace(2.2,10.2,7,endpoint=False)

array([2.2       , 3.34285714, 4.48571429, 5.62857143, 6.77142857,
       7.91428571, 9.05714286])

In [18]:
np.linspace(2.2,10.2,7.5,endpoint=False)

TypeError: 'float' object cannot be interpreted as an integer

In [19]:
np.linspace(2.2,10.2,7)

array([ 2.2       ,  3.53333333,  4.86666667,  6.2       ,  7.53333333,
        8.86666667, 10.2       ])

In [20]:
np.linspace(2.2,10.2,7,endpoint=bool)

array([ 2.2       ,  3.53333333,  4.86666667,  6.2       ,  7.53333333,
        8.86666667, 10.2       ])

In [21]:
np.linspace(2.2,10.2,7,endpoint=bool,dtype=complex)

array([ 2.2       +0.j,  3.53333333+0.j,  4.86666667+0.j,  6.2       +0.j,
        7.53333333+0.j,  8.86666667+0.j, 10.2       +0.j])

In [23]:
np.linspace(2.2,10.2,num=10,endpoint=bool,dtype=int)

array([ 2,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.linspace(2.2,10.2,num=10,endpoint=bool,dtype=float)

array([ 2.2       ,  3.08888889,  3.97777778,  4.86666667,  5.75555556,
        6.64444444,  7.53333333,  8.42222222,  9.31111111, 10.2       ])

In [24]:
np.linspace(2.2,15,num=10,endpoint=bool,dtype=int)

array([ 2,  3,  5,  6,  7,  9, 10, 12, 13, 15])

In [28]:
np.array(np.array())

TypeError: array() missing required argument 'object' (pos 0)

In [29]:
np.array(np.array({a:1}))

NameError: name 'a' is not defined

In [30]:
np.array(np.array([1,2,2,2]))

array([1, 2, 2, 2])

In [31]:
x = np.array([1,2,3,4,5])
np.array(x)

array([1, 2, 3, 4, 5])

In [32]:
x = np.array([1,2,3,4,5])
np.array([x,22,33,44,55])

C:\Users\user\AppData\Local\Temp\ipykernel_324\1693542632.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([x,22,33,44,55])


array([array([1, 2, 3, 4, 5]), 22, 33, 44, 55], dtype=object)

In [33]:
x = {a:1,b:2}
np.array([x,22,33,44,55])

NameError: name 'a' is not defined

In [35]:
x = {"a":1,"b":2}
np.array([x,22,33,44,55])

array([{'a': 1, 'b': 2}, 22, 33, 44, 55], dtype=object)

In [34]:
x = {1:"Aj",2:"SS"}
np.array([x,22,33,44,55])

array([{1: 'Aj', 2: 'SS'}, 22, 33, 44, 55], dtype=object)

In [36]:
x = {1:"Aj",2:"SS"}
y = np.array([11,22,33,44])
z = True
a = 5 + j
b = 7.7
np.array([x,y,z,a,b])

NameError: name 'j' is not defined

In [38]:
x = {1:"Aj",2:"SS"}
y = np.array([11,22,33,44])
z = True
a = (1,2,3,4)
b = 7.7
np.array([x,y,z,a,b])

C:\Users\user\AppData\Local\Temp\ipykernel_324\1285327039.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([x,y,z,a,b])


array([{1: 'Aj', 2: 'SS'}, array([11, 22, 33, 44]), True, (1, 2, 3, 4),
       7.7], dtype=object)