<font size = 5.5>Shape Manipulation in NumPy
    <br> <br> .reshape()
    <br> .flatten() 
    <br> .ravel()
    <br> -- Stacking
    <br> -- Concatenation

In [1]:
import numpy as np

In [2]:
## .reshape()
x = np.array([1,2,3,4])
print(x.shape)
x = x.reshape(2,2)      ## Create a copy of the ndarray
x

(4,)


array([[1, 2],
       [3, 4]])

In [7]:
x.reshape(1,1,2,2,1)

array([[[[[1],
          [2]],

         [[3],
          [4]]]]])

In [8]:
## .flatten()         #### Creates a copy object.....
x.flatten()

array([1, 2, 3, 4])

In [9]:
x

array([[1, 2],
       [3, 4]])

In [5]:
## .ravel()            #### Creates a view object......
x.ravel()

array([1, 2, 3, 4])

In [8]:
x

array([[1, 2],
       [3, 4]])

<Font size = 5.5> .resize()  --- Makes changes in the original array...or stores the value in array...

In [10]:
## .resize()  -- Just like .reshape....but there is a difference...
x.resize(4,1)

In [11]:
x            ### changed the original array

array([[1],
       [2],
       [3],
       [4]])

In [12]:
x.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [11]:
x.reshape

<function ndarray.reshape>

In [13]:
x.reshape(2,2)           ### No changes in the original array....IMPORTANT....
x

array([[1],
       [2],
       [3],
       [4]])

<Font size = 5.5> Stacking of Arrays 

In [13]:
x = np.array([[1,2],[3,8]])
y = np.array([[5,6],[7,9]])

x.stack(y)

AttributeError: 'numpy.ndarray' object has no attribute 'stack'

<Font Size = 5.5> 26 Sept 2023

In [12]:
import numpy as np

<Font size = 5.5> Stacking  -- Join a sequence of arrays along a new axis 

In [14]:
## Stack
## 2-D
n1 = np.array([[1,2,4],
             [5,6,7]])
n2 = np.array([[8,9,10],
             [11,12,13]])
print(f"n1 : \n {n1} \nn2 : \n {n2} \n")
print("for axis = 0 \n", np.stack((n1,n2),axis = 0), "\n" )  ### Row-wise stacking

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 

for axis = 0 
 [[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]] 



In [15]:
print(f"n1 : \n {n1} \nn2 : \n {n2} \n")
print("for axis = 1 \n", np.stack((n1,n2),axis = 1), "\n" )  ### Colunm-wise stacking

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 

for axis = 1 
 [[[ 1  2  4]
  [ 8  9 10]]

 [[ 5  6  7]
  [11 12 13]]] 



In [5]:
## Syntax for stacking...
np.stack((n1,n2),axis = 1)

array([[[ 1,  2,  4],
        [ 8,  9, 10]],

       [[ 5,  6,  7],
        [11, 12, 13]]])

In [16]:
## .stack()
### 1-D
x1 = np.array([1,2,3,4,56,88])
x2 = np.array([6,7,8,9,33,55])
print(f"x1 : \n {x1} \nx2 : \n {x2} \n")
print(np.stack((x1,x2),axis = 0)), print("\n")
print(f"x1 : \n {x1} \nx2 : \n {x2} \n")
print(np.stack((x1,x2),axis = 1))
np.stack((x1,x2),axis = 1)

x1 : 
 [ 1  2  3  4 56 88] 
x2 : 
 [ 6  7  8  9 33 55] 

[[ 1  2  3  4 56 88]
 [ 6  7  8  9 33 55]]


x1 : 
 [ 1  2  3  4 56 88] 
x2 : 
 [ 6  7  8  9 33 55] 

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [56 33]
 [88 55]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [56, 33],
       [88, 55]])

In [17]:
## .stack()
### 1-D
x1 = np.array([1,2,3,4])
x2 = np.array([6,7,8,9])
x3 = np.array([11,22,33,44])
print(f"x1 : \n {x1} \nx2 : \n {x2} \nx3 : \n {x3} \n")
print(np.stack((x1,x2,x3),axis = 0)), print("\n")
print(f"x1 : \n {x1} \nx2 : \n {x2} \nx3 : \n {x3} \n")
print(np.stack((x1,x2,x3),axis = 1))
np.stack((x1,x2,x3),axis = 1)

x1 : 
 [1 2 3 4] 
x2 : 
 [6 7 8 9] 
x3 : 
 [11 22 33 44] 

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 22 33 44]]


x1 : 
 [1 2 3 4] 
x2 : 
 [6 7 8 9] 
x3 : 
 [11 22 33 44] 

[[ 1  6 11]
 [ 2  7 22]
 [ 3  8 33]
 [ 4  9 44]]


array([[ 1,  6, 11],
       [ 2,  7, 22],
       [ 3,  8, 33],
       [ 4,  9, 44]])

In [18]:
## Stack
## 2-D
n1 = np.array([[1,2,4],
             [5,6,7]])
n2 = np.array([[8,9,10],
             [11,12,13]])
n3 = np.array([[1,1,1],
             [2,2,2]])
print(f"n1 : \n {n1} \nn2 : \n {n2} \nn3 : \n {n3} \n")
print("for axis = 0 \n", np.stack((n1,n2,n3),axis = 0), "\n" )  ### Row-wise stacking
print(f"n1 : \n {n1} \nn2 : \n {n2} \nn3 : \n {n3} \n")
print("for axis = 1 \n", np.stack((n1,n2,n3),axis = 1), "\n" )  ### Colunm-wise stacking

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 
n3 : 
 [[1 1 1]
 [2 2 2]] 

for axis = 0 
 [[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[ 1  1  1]
  [ 2  2  2]]] 

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 
n3 : 
 [[1 1 1]
 [2 2 2]] 

for axis = 1 
 [[[ 1  2  4]
  [ 8  9 10]
  [ 1  1  1]]

 [[ 5  6  7]
  [11 12 13]
  [ 2  2  2]]] 



In [1]:
import numpy as np

<Font size = 5.5> Concatenation -- Joining of arrays along an existing axis.

In [10]:
### Concatenation
## 2-D
n1 = np.array([[1,2,4],
             [5,6,7]])
n2 = np.array([[8,9,10],
             [11,12,13]])
print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis = 0 \n", np.concatenate((n1,n2),axis = 0), "\n" )  ### Row-wise Concatenation
print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis = 1 \n", np.concatenate((n1,n2),axis = 1), "\n" )  ### Colunm-wise Concatenation

n1: 
 [[1 2 4]
 [5 6 7]] 
n2: 
 [[ 8  9 10]
 [11 12 13]] 

for axis = 0 
 [[ 1  2  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]] 

n1: 
 [[1 2 4]
 [5 6 7]] 
n2: 
 [[ 8  9 10]
 [11 12 13]] 

for axis = 1 
 [[ 1  2  4  8  9 10]
 [ 5  6  7 11 12 13]] 



In [13]:
### Concatenation
## 1-D
n1 = np.array([1,2,4,5])
n2 = np.array([8,9,10,11])
print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis = 0 \n", np.concatenate((n1,n2),axis = 0), "\n" )  ### Row-wise Concatenation

n1: 
 [1 2 4 5] 
n2: 
 [ 8  9 10 11] 

for axis = 0 
 [ 1  2  4  5  8  9 10 11] 



In [14]:
print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis = 1 \n", np.concatenate((n1,n2),axis = 1), "\n" )  ### Colunm-wise Concatenation

n1: 
 [1 2 4 5] 
n2: 
 [ 8  9 10 11] 



AxisError: axis 1 is out of bounds for array of dimension 1

<font size = 5.5> hstack (Horizontal-stacking) and vstack (Vertical-Stacking)

In [16]:
##  2D -array
x = np.array([[1,2,3,4],
              [5,6,7,8]])
y = np.array([[11,22,33,44],
              [88,77,66,55]])

In [17]:
np.hstack((x,y))            ## np.concatenate((x,y), axis =1)

array([[ 1,  2,  3,  4, 11, 22, 33, 44],
       [ 5,  6,  7,  8, 88, 77, 66, 55]])

In [18]:
np.vstack((x,y))           ## np.concatenate((x,y), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44],
       [88, 77, 66, 55]])

In [15]:
## 1D - Array.....
x1 = np.array([1,2,3,4])
x2 = np.array([11,22,33,44])

In [16]:
np.hstack((x1,x2))         ## np.concatenate((x1,x2), axis = 0)

array([ 1,  2,  3,  4, 11, 22, 33, 44])

In [21]:
np.vstack((x1,x2))        ## np.stack((x1,x2), axis = 0)

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

<Font Size = 5.5> Indexing, Slicing and Striding

In [23]:
## 1D - Array
## (AXIS 0,)
### (COLUMNS,)
##  (0D, )
x = np.array([1,2,3,4,5])
print(x[1])
print(x[4])

2
5


In [25]:
## 2D - Array
## (AXIS 0 , AXIS 1)
## (ROWS, COLUMNS)
### (1D, 0D)
xx = np.array([[11,22,33,44],
               [55,66,77,88]])
xx[1,3]        ## Preferred Way

88

In [26]:
xx[1][3]       ## ALtenative Way

88

In [28]:
xx[0,-1]

44

In [29]:
xx[-2,-3]

22

In [30]:
xx[-2,-2]

33

In [33]:
xx[1,-1],xx[-1,-4],xx[-2,-4]

(88, 55, 11)

<Font Size = 5.5> 03 OCT 2023

In [16]:
import numpy as np

In [17]:
x = np.array([[[1,2,3],
              [4,5,6]],
             [[7,8,9],
             [10,11,12]]])
x.shape,x.ndim

((2, 2, 3), 3)

In [6]:
x[0,1,2],x[1,1,2],x[1,0,1]

(6, 12, 8)

In [17]:
xx = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [8]:
xx[1,2,2],xx[1]

(18,
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [9]:
xx[0,0]

array([1, 2, 3])

In [10]:
xx[0,1]

array([4, 5, 6])

In [11]:
xx[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
xx[1,2,1],xx[1,2,2],xx[0,2,1]

(17, 18, 8)

In [18]:
###  3D
### (AXIS 0, AXIS 1, AXIS 2)
### (2D    , 1D    , 0D)
### (A0    , A1    , A2)

a = np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[9,10,11,12],
              [13,14,15,16]]])
a[0],a[1]

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]))

In [19]:
a[1,1,3],a[1,1,0],a[0,1,3]

(16, 13, 8)

In [24]:
a[1,1]

array([13, 14, 15, 16])

In [29]:
a[0,1,2],a[1,1,2],a[1,1,3]

(7, 15, 16)

In [30]:
###  3D
### (AXIS 0, AXIS 1, AXIS 2)
### (2D    , 1D    , 0D)
### (A0    , A1    , A2)

a = np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[9,10,11,12],
              [13,14,15,16]]])
a[0],a[1],a[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [19]:
a[2,2,2],a[3,3,3],a[1,2,3]

IndexError: index 2 is out of bounds for axis 0 with size 2

<Font size = 5.5> Example of 4D Array.......

In [34]:
### 4D
### (AXIS 0, AXIS 1, AXIS 2, AXIS 3)
### (3D    ,2D     ,1D     ,0D)
### xxx[3d,2d,1d,0d]
xxx = np.array([[[[1,2]],
         [[3,4]]],
      [[[5,6]],
       [[7,8]]]])

In [35]:
### xxx[3d,2d,1d,0d]
xxx[1,1,0,0]

7

In [38]:
xxx.shape,xxx.size,xxx.ndim

((2, 2, 1, 2), 8, 4)

<Font Size = 5.5> Slicing and Striding
    <br><font size = 4> start(inclusive) : stop (exclusive) : (step)

In [32]:
### 1D

s = np.array([1,2,3,4,5,6,7,8])
s[0:8:2],s[0:8:3]

(array([1, 3, 5, 7]), array([1, 4, 7]))

In [34]:
s[::3],s[::2]

(array([1, 4, 7]), array([1, 3, 5, 7]))

In [31]:
### 2D 
ss = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12],
             [-1,-2,-3,-4]])
ss[::2],ss[::3]

(array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [-1, -2, -3, -4]]))

In [40]:
ss[::],ss[::1]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [-1, -2, -3, -4]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [-1, -2, -3, -4]]))

In [43]:
ss[::-1],ss[::-2]

(array([[-1, -2, -3, -4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]]),
 array([[-1, -2, -3, -4],
        [ 5,  6,  7,  8]]))

In [52]:
### 2D 
ss = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12],
             [-1,-2,-3,-4]])

In [56]:
ss[::2,1],ss[::,3],ss[::,-2]

(array([ 2, 10]), array([ 4,  8, 12, -4]), array([ 3,  7, 11, -3]))

<font size = 5.5> Something New!

In [32]:
ss[2:0:4]

array([], shape=(0, 4), dtype=int32)

In [33]:
ss[2:0:5]

array([], shape=(0, 4), dtype=int32)

<FOnt Size = 5.5> 4 OCT 2023

<Font Size = 5.5> Slicing

In [1]:
import numpy as np

In [7]:
### 2D Array
x = np.array([[1,2,3],
              [4,5,6]])

x[0:2,0:2], x[0:2,0], x[0,1:3]

(array([[1, 2],
        [4, 5]]),
 array([1, 4]),
 array([2, 3]))

In [10]:
x[0:2,1], x[1,0:2], x[0,0:2]

(array([2, 5]), array([4, 5]), array([1, 2]))

In [12]:
x[0,0:3],x[0,:2]

(array([1, 2, 3]), array([1, 2]))

In [14]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x[::,0:2],x[::,::]

(array([[1, 2],
        [4, 5]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [18]:
x[::,:2:2],x[::-1,:2:2]

(array([[1],
        [4]]),
 array([[4],
        [1]]))

In [42]:
### 2D Array

xx = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
xx[1:3,1:3],xx[2:4,2:4],xx[1:3,:3],xx[1:3,3:]

(array([[ 6,  7],
        [10, 11]]),
 array([[11, 12],
        [15, 16]]),
 array([[ 5,  6,  7],
        [ 9, 10, 11]]),
 array([[ 8],
        [12]]))

In [43]:
xx[2,1:3], xx[3,1:3], xx[1:3,3], xx[1:3,0]

(array([10, 11]), array([14, 15]), array([ 8, 12]), array([5, 9]))

<Font Size  = 5.5> Replacing the values in an ARRAY....

In [34]:
xx = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

In [35]:
xx[2,1:3] = [444,555]
xx[0:2,3] = [1111,2222]
xx

array([[   1,    2,    3, 1111],
       [   5,    6,    7, 2222],
       [   9,  444,  555,   12],
       [  13,   14,   15,   16]])

In [47]:
### 3D ARRAY

a = np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]]])
a[0,0:2,0:2]

array([[1, 2],
       [3, 4]])

<Font Size = 6> Errors

In [13]:
x[,]

SyntaxError: invalid syntax (2630041655.py, line 1)

In [15]:
x[,:]

SyntaxError: invalid syntax (81718787.py, line 1)

In [27]:
### 2D Array

xx = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
xx[1:3,1:3],xx[2:4,2:4],xx[1:3,:3]
,xx[1:3,3:]

TypeError: 'numpy.ndarray' object is not callable

In [39]:
xx[2,1:3] = [444,555], xx[0:2,3] = [1111,2222]
xx

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (1979164292.py, line 1)

In [40]:
xx[2,1:3] = [444,555] xx[0:2,3] = [1111,2222]
xx

SyntaxError: invalid syntax (376872080.py, line 1)

In [45]:
### 3D ARRAY

a = np.array[[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]

TypeError: 'builtin_function_or_method' object is not subscriptable