<font size = 5.5> NumPy -- Numerical PYthon <br> <font size = 4.5> Introduction to NumPy <font size = 3.5> <br> <li> It is a PYthon library used for working with arrays. <br> <li> It consists of a multidimensional array of objects and a collection of functions for manipulating them. <br> <li> It conducts mathematical and logical operations on arrays.

<font size = 5.5> Advantages of NumPy  <br> <font size = 4> The following are the advantages of NumPy: <font size = 3.5> <br> It provides an array objrcts that is faster than traditional PYthon lists. <br> It provides supporting functions. <br> Arrays are fequently used in data science.

<font size = 5.5> What is an Array?  <br> <font size = 4> <li> An Array is a central data structure of the NumPy Library. <br> <li> It is a grid of homogeneous values (same data types) <br> <li> The **rank** of the array is the number of dimensions. <br> <li> The array ojects in NumPy is called **ndarray**  (n - dimensional array)

In [2]:
import numpy as np

In [3]:
# Importing NumPy

import numpy as np
aj = np.array([1,2,3,4,5])            ## Creating an ndarray
print(aj)
aj

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
aj = np.array((1,2,3,4,5))            ## Creating an ndarray
print(aj)
aj

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [4]:
aj = np.array({1,2,3,4,5})            ## Creating an ndarray
print(aj)
aj

{1, 2, 3, 4, 5}


array({1, 2, 3, 4, 5}, dtype=object)

In [6]:
print(type(aj))
type(aj)

<class 'numpy.ndarray'>


numpy.ndarray

In [7]:
aj = np.array({a:1,2,3,4,5})            ## Creating an ndarray
print(aj)
aj

SyntaxError: ':' expected after dictionary key (3902200549.py, line 1)

In [8]:
aj = np.array({a:"1"},{b:"2"})            ## Creating an ndarray
print(aj)
aj

NameError: name 'a' is not defined

In [9]:
aj = np.array({1:1,2,3,4,5},{11:5,5,6,7})            ## Creating an ndarray
print(aj)
aj

SyntaxError: ':' expected after dictionary key (1512545148.py, line 1)

In [4]:
aj = np.array({1:"55"},{11:"11"})            ## Creating an ndarray
print(aj)
aj

ValueError: entry not a 2- or 3- tuple

In [11]:
aj = np.array({1:"55",11:"11"})            ## Creating an ndarray
print(aj)
aj

{1: '55', 11: '11'}


array({1: '55', 11: '11'}, dtype=object)

In [12]:
aj = np.array({1:"55",11:"11",111:"Arj"})            ## Creating an ndarray
print(aj)
aj

{1: '55', 11: '11', 111: 'Arj'}


array({1: '55', 11: '11', 111: 'Arj'}, dtype=object)

In [13]:
aj = np.array([1,2,3,4,5,"Arj",True])            ## Creating an ndarray
print(aj)
aj

['1' '2' '3' '4' '5' 'Arj' 'True']


array(['1', '2', '3', '4', '5', 'Arj', 'True'], dtype='<U11')

In [14]:
aj = np.array([1,2,3,4,5,"Arj",True,111.111])            ## Creating an ndarray
print(aj)
aj

['1' '2' '3' '4' '5' 'Arj' 'True' '111.111']


array(['1', '2', '3', '4', '5', 'Arj', 'True', '111.111'], dtype='<U32')

In [15]:
aj = np.array([True,False,False,True,True,True])            ## Creating an ndarray
print(aj)
aj

[ True False False  True  True  True]


array([ True, False, False,  True,  True,  True])

In [16]:
aj = np.array([True,False,111,True,True,True])            ## Creating an ndarray
print(aj)
aj

[  1   0 111   1   1   1]


array([  1,   0, 111,   1,   1,   1])

In [17]:
aj = np.array("Ajsstavinomi")            ## Creating an ndarray
print(aj)
aj

Ajsstavinomi


array('Ajsstavinomi', dtype='<U12')

In [18]:
aj = np.array("Aj", "ss", "tavi", "nomi")            ## Creating an ndarray
print(aj)
aj

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [19]:
aj = np.array("Aj", "ss")            ## Creating an ndarray
print(aj)
aj

TypeError: data type 'ss' not understood

In [20]:
aj = np.array(["Aj", "ss", "tavi", "nomi"])            ## Creating an ndarray
print(aj)
aj                                          #######   dtype  == data type

['Aj' 'ss' 'tavi' 'nomi']


array(['Aj', 'ss', 'tavi', 'nomi'], dtype='<U4')

<font size = 5.5> 9th Sept 2023

In [1]:
## Creating a zero dimensional array

import numpy as np
arr = np.array("55")
print(arr)

55


In [3]:
## Creating a one dimensional array

import numpy as np
arr = np.array([55,1,2,3,77])
print(arr)

[55  1  2  3 77]


In [4]:
## Creating a two dimensional array

import numpy as np
arr = np.array([[55,1,2,3,77],[873,837,648,4454]])          ### Number of Items in the Lists are different....
print(arr)

[list([55, 1, 2, 3, 77]) list([873, 837, 648, 4454])]


C:\Users\user\AppData\Local\Temp\ipykernel_2716\101348641.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[55,1,2,3,77],[873,837,648,4454]])


In [5]:
## Creating a two dimensional array

import numpy as np
arr = np.array([[55,1,2,3,77],[3,7,8,44]])       ### Number of Items in the Lists are different....
print(arr)

[list([55, 1, 2, 3, 77]) list([3, 7, 8, 44])]


C:\Users\user\AppData\Local\Temp\ipykernel_2716\247639914.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[55,1,2,3,77],[3,7,8,44]])


In [6]:
## Creating a two dimensional array

import numpy as np
arr = np.array([[5,1,2,3,7],[3,7,8,4]])        ### Number of Items in the Lists are different....
print(arr)

[list([5, 1, 2, 3, 7]) list([3, 7, 8, 4])]


C:\Users\user\AppData\Local\Temp\ipykernel_2716\97711537.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[5,1,2,3,7],[3,7,8,4]])


In [7]:
## Creating a two dimensional array

import numpy as np
arr = np.array([[55,1,2,3],[873,837,648,4454]])
print(arr)

[[  55    1    2    3]
 [ 873  837  648 4454]]


In [8]:
## Creating a two dimensional array

import numpy as np
arr = np.array([["AJ","SS","Ta","Nm","We"],["Ra","MAa","Paa","JAa"]])    ### Number of Items in the Lists are different....
print(arr)

[list(['AJ', 'SS', 'Ta', 'Nm', 'We']) list(['Ra', 'MAa', 'Paa', 'JAa'])]


C:\Users\user\AppData\Local\Temp\ipykernel_2716\373789477.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([["AJ","SS","Ta","Nm","We"],["Ra","MAa","Paa","JAa"]])


In [9]:
## Creating a two dimensional array

import numpy as np
arr = np.array([["AJ","SS","Ta","Nm"],["Ra","MAa","Paa","JAa"]])
print(arr)

[['AJ' 'SS' 'Ta' 'Nm']
 ['Ra' 'MAa' 'Paa' 'JAa']]


In [12]:
## Creating a three dimensional array

import numpy as np
arr = np.array([ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ])
print(arr)

[[[5 1 2 3]
  [3 7 8 4]]

 [[1 2 3 4]
  [6 7 8 9]]]


In [14]:
## Creating a Four dimensional array

import numpy as np
arr = np.array([[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]])
print(arr)

[[[[1 2 3 4]
   [3 4 5 6]]

  [[1 2 3 4]
   [6 7 8 9]]]


 [[[5 1 2 3]
   [3 7 8 4]]

  [[1 2 3 4]
   [6 7 8 9]]]]


In [17]:
## Creating a Five dimensional array

import numpy as np
arr = np.array([[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]],[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]]])
print(arr)

[[[[[1 2 3 4]
    [3 4 5 6]]

   [[1 2 3 4]
    [6 7 8 9]]]


  [[[5 1 2 3]
    [3 7 8 4]]

   [[1 2 3 4]
    [6 7 8 9]]]]



 [[[[1 2 3 4]
    [3 4 5 6]]

   [[1 2 3 4]
    [6 7 8 9]]]


  [[[5 1 2 3]
    [3 7 8 4]]

   [[1 2 3 4]
    [6 7 8 9]]]]]


In [18]:
## Creating a six dimensional array

import numpy as np
arr = np.array([[[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]],[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]]],
[[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]],[[ [ [1,2,3,4], [3,4,5,6] ] , [ [1,2,3,4] , [6,7,8,9] ] ],[ [ [5,1,2,3], [3,7,8,4] ] , [ [1,2,3,4] , [6,7,8,9] ] ]]]])
print(arr)

[[[[[[1 2 3 4]
     [3 4 5 6]]

    [[1 2 3 4]
     [6 7 8 9]]]


   [[[5 1 2 3]
     [3 7 8 4]]

    [[1 2 3 4]
     [6 7 8 9]]]]



  [[[[1 2 3 4]
     [3 4 5 6]]

    [[1 2 3 4]
     [6 7 8 9]]]


   [[[5 1 2 3]
     [3 7 8 4]]

    [[1 2 3 4]
     [6 7 8 9]]]]]




 [[[[[1 2 3 4]
     [3 4 5 6]]

    [[1 2 3 4]
     [6 7 8 9]]]


   [[[5 1 2 3]
     [3 7 8 4]]

    [[1 2 3 4]
     [6 7 8 9]]]]



  [[[[1 2 3 4]
     [3 4 5 6]]

    [[1 2 3 4]
     [6 7 8 9]]]


   [[[5 1 2 3]
     [3 7 8 4]]

    [[1 2 3 4]
     [6 7 8 9]]]]]]


In [16]:
aarr = np.array([[],[],[],[]])
aarr

array([], shape=(4, 0), dtype=float64)

In [21]:
arr3 = np.array([[[1,2],[3,4],
          [5,6],[2,3]],
          [[4,5],[5,6],
           [6,7],[8,9]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [2, 3]],

       [[4, 5],
        [5, 6],
        [6, 7],
        [8, 9]]])

In [22]:
arr3 = np.array([[[1,2],[3,4],
          [5,6],[2,3]],
          [[4,5],
           [6,7],[8,9]]])            ### Number of Items in the Lists are different....
arr3

C:\Users\user\AppData\Local\Temp\ipykernel_2716\4115363636.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[[1,2],[3,4],


array([list([[1, 2], [3, 4], [5, 6], [2, 3]]),
       list([[4, 5], [6, 7], [8, 9]])], dtype=object)

In [23]:
### What could be another way to create an array
y = [1,2,3,4]
x = np.array(y)
x

array([1, 2, 3, 4])

In [24]:
### What could be another way to create an array
y = [1,2,3,4]
x = np.array(range(5))
x

array([0, 1, 2, 3, 4])

In [25]:
### What could be another way to create an array
y = [1,2,3,4]
x = np.array([range(4),y])
x

array([[0, 1, 2, 3],
       [1, 2, 3, 4]])

In [26]:
### What could be another way to create an array
y = [1,2,3,4]
y1 = [2,3,4,5]
y2 = [3,4,5,6]
y3 = [4,5,6,7]
x = np.array([[y],[y1]])
x

array([[[1, 2, 3, 4]],

       [[2, 3, 4, 5]]])

In [27]:
x.ndim

3

In [28]:
x1 = np.array([[[[[[1,2,3,4]]]]]])
x1.ndim

6

In [29]:
x1 = np.array([[[[1,2,3,4]]]])
x1.ndim

4

In [30]:
x5 = np.array([[[[[[[[[[[[[[[]]]]]]]]]]]]]]])
x5.ndim

15

In [32]:
ra = np.array(range(5))
ra

array([0, 1, 2, 3, 4])

In [7]:
my_arr = np.arange(100000)
my_list = list(range(100000))
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [37]:
%timeit my_arr2 = my_arr * 2

123 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


<font size = 5.5> Important Example

In [39]:
%timeit my_list2 = [x*2 for x in my_list]

9.11 ms ± 395 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [40]:
[1,2,3,4,5]*2         ##### Items of the list are printed TWO times in the same list........

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
[1,2,3,4,5]*5         ##### Items of the list are printed FIVE times in the same list........

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
L1 = [1,2,3,4,5,6]
L1 = L2

NameError: name 'L2' is not defined

In [15]:
L1 = [1,2,3,4,5,6]
L2 = L1
L2[5] = 111
L1,L2

([1, 2, 3, 4, 5, 111], [1, 2, 3, 4, 5, 111])

In [17]:
L2 = L1.copy()
L2
L2[2] = 999
L2,L1

([1, 2, 999, 4, 5, 111], [1, 2, 3, 4, 5, 111])

In [41]:
[1,2,3,4,5]/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [43]:
[1,2,3,4,5]//2

TypeError: unsupported operand type(s) for //: 'list' and 'int'

In [3]:
S2 = {1,1,1,1,1,1,1}
S2

{1}

In [1]:
S1 = {[1,2,3,4]}

TypeError: unhashable type: 'list'

In [6]:
S1 = {(1,2,3,3,4)}
S1

{(1, 2, 3, 3, 4)}

In [8]:
# Importing NumPy

import numpy as np

In [9]:
ARR = np.array("Aj", 1, 5.55, True, False , None, (1,2,3), [1,2,3,4], 4+5j)

TypeError: array() takes from 1 to 2 positional arguments but 9 were given

In [10]:
ARR = np.array("Aj", 1, 5.55, True, False , None)

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [13]:
ARR = np.array(["Aj", 1, 5.55, True, False , None, (1,2,3), [1,2,3,4], 4+5j])

C:\Users\user\AppData\Local\Temp\ipykernel_1160\3612580299.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ARR = np.array(["Aj", 1, 5.55, True, False , None, (1,2,3), [1,2,3,4], 4+5j])


In [12]:
ARR = np.array(["Aj", 1, 5.55, True, False , None])
ARR

array(['Aj', 1, 5.55, True, False, None], dtype=object)