<Font size = 5.5> Boolean Array 

In [1]:
import numpy as np
names = np.array(["Aj","SS","Tav","Aj","SS","Nomi"])

In [11]:
names == "Aj"  ### This gives a Boolean Array

array([ True, False, False,  True, False, False])

In [12]:
names[names == "Aj"]   ### Here dtype ='<U4 in dtype = number of characters in string.....i.e. Nomi is having "4" characters...

array(['Aj', 'Aj'], dtype='<U4')

In [14]:
names[names == "Aj"][3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [15]:
names[names == "Aj"][0]

'Aj'

In [4]:
n = np.array([1,2,3,3,3,4,5,6,7])
n <= 5

array([ True,  True,  True,  True,  True,  True,  True, False, False])

In [5]:
n [n<=5]

array([1, 2, 3, 3, 3, 4, 5])